---
  - name:  OpenStack Service_neutron-server
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: Create DB
      mysql_db:
        name: "{{ item }}"
        state: present
      with_items:
        - neutron

    - name: Update mysql neutron-server password for all accounts
      no_log: true
      mysql_user:
         name: neutron
         host: "{{ item.host }}"
         password: "{{ db_password }}"
         priv: '{{ item.db }}.*:ALL'
         state: present
         append_privs: yes
      with_items:
         - db: neutron
           host: localhost
         - db: neutron
           host: '%'
