---
  - name:  OpenStack nova compute service add 
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: nova-compute discover_host
      command: /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" 
