---
  - name: nova-compute ovs-agnet && neutron config setting
    hosts: compute 
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: neutron-compute config file setting 
      template: 
        src: "{{ template_files }}" 
        dest: /etc/neutron/neutron.conf
        owner: root
        group: neutron
        mode: 0640
        backup: yes
      with_items:
        ['neutron.conf.j2']

    - name: neutron-compute config file setting
      template:
        src: "{{ template_files }}"
        dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
        owner: root
        group: neutron
        mode: 0644
        backup: yes
      with_items:
        ['openvswitch_agent.ini.j2']
