---
 - name: HA_cluster init
   hosts: haproxy01
   become: true
   vars_files:
    - /root/okestroiaas/variable/common_vars/main.yml
   tasks:
   - name: pcs cluster destroy
     command: pcs cluster destroy

   - name: Pause for 5 seconds to pcs cluster destroy
     pause:
       seconds: 5
   
   - name: HA cluster user intigration
     command: pcs host auth {{ member }} -u hacluster -p hauser1234

   - name: HA cluster setup
     command: pcs cluster setup haproxy {{ member }} --start --enable --force

   - name: pcs start all && enable
     command: "{{ item }}"
     with_items:
     - pcs cluster start --all
     - pcs cluster enable --all

   - name: resource create
     command: "{{ item }}"
     with_items:
     - pcs property set stonith-enabled=false
     - pcs property set no-quorum-policy=ignore

   - name: create vip
     command: "{{ item }}"
     with_items:
     - pcs resource create vip ocf:heartbeat:IPaddr2 ip={{ bind_ip }} nic={{ bind_nic }} cidr_netmask=24 op monitor interval=10s

   - name: haproxy resource && clone
     command: "{{ item }}"
     with_items:
     - pcs resource create haproxy systemd:haproxy op monitor interval=20s timeout=20
     - pcs constraint order start vip then haproxy kind=Optional
     - pcs constraint colocation add haproxy with vip
