---
  - name:  OpenStack Service_nova-api
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    environment:
       OS_PROJECT_DOMAIN_NAME: Default
       OS_USER_DOMAIN_NAME: Default
       OS_PROJECT_NAME: admin
       OS_USERNAME: admin
       OS_PASSWORD: "{{ keystone_pass }}"
       OS_AUTH_URL: http://{{ bind_ip }}:15000/v3/
       OS_IDENTITY_API_VERSION: 3
       OS_IMAGE_API_VERSION: 2
    tasks:
    - name: Create user
      command: openstack user create --domain default --password {{ keystone_pass }} nova 
      ignore_errors: True

    - name: nova-api role add 
      command: openstack role add --project service --user nova admin 
      ignore_errors: True

    - name: Create the nova service entity
      command: openstack service create --name nova --description "OpenStack Compute" compute
      ignore_errors: True

    - name: Create user
      command: openstack user create --domain default --password {{ keystone_pass }} placement
      ignore_errors: True

    - name: placement role add
      command: openstack role add --project service --user placement admin

    - name: Create the placement service entity
      command: openstack service create --name placement --description "Placement API" placement 

