---
  - name:  OpenStack Service_octavia-api
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    environment:
       OS_PROJECT_DOMAIN_NAME: Default
       OS_USER_DOMAIN_NAME: Default
       OS_PROJECT_NAME: admin
       OS_USERNAME: admin
       OS_PASSWORD: "{{ keystone_pass }}"
       OS_AUTH_URL: http://{{ bind_ip }}:15000/v3/
       OS_IDENTITY_API_VERSION: 3
       OS_IMAGE_API_VERSION: 2
    tasks:
    - name: Create user
      command: openstack user create --domain default --password {{ keystone_pass }} octavia 

    - name: octavia-api role add service
      command: openstack role add --project service --user octavia admin 

    - name: octavia-api role add admin
      command: openstack role add --project admin --user octavia admin 

    - name: Create the octavia service entity
      command: openstack service create --name octavia --description "OpenStack Octavia" load-balancer



