---
  - name:  OpenStack Service_octavia-api install
    hosts: controller
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: octavia-api_pakage_install  
      yum:
        name: 
          - openstack-octavia-api
          - openstack-octavia-health-manager
          - openstack-octavia-housekeeping
          - openstack-octavia-worker
          - python3-octaviaclient
          - openstack-octavia-ui.noarch
        state: present
