  - name: create dhclient 
    hosts: controller
    tasks:
    - name: create directory octavia
      file: 
        path: /etc/dhcp/octavia
        state: directory
        mode: '0755'
    - name: inline file dhclient file
      copy:
        owner: octavia
        group: octavia
        mode: u+rwx,g+rx,o+rx
        content: "request subnet-mask,broadcast-address,interface-mtu;\ndo-forward-updates false;"
        dest: /etc/dhcp/octavia/dhclient.conf

    - name: o-hm0 interface ip allocated
      shell: dhclient -v o-hm0 -cf /etc/dhcp/octavia/dhclient.conf	
