---
  - name:  OpenStack Service_Keystone
    hosts: controller
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: Enable and start Apache.
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: Enable Apache service
      systemd:
        name: httpd
        enabled: yes
        masked: no
