---
  - name:  OpenStack Service_cinder
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: DB sync
      changed_when: no
      command: /bin/sh -c "cinder-manage db sync" 

