---
  - name:  OpenStack Service_cinder
    hosts: controller
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: cinder_pakage_install
      yum:
        update_cache: yes
        name:
          - openstack-cinder
        state: present
