---
  - name:  OpenStack Service_cinder
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    environment:
       OS_PROJECT_DOMAIN_NAME: Default
       OS_USER_DOMAIN_NAME: Default
       OS_PROJECT_NAME: admin
       OS_USERNAME: admin
       OS_PASSWORD: "{{ keystone_pass }}"
       OS_AUTH_URL: http://{{ bind_ip }}:15000/v3/
       OS_IDENTITY_API_VERSION: 3
       OS_IMAGE_API_VERSION: 2
    tasks:
    - name: Create user
      command: openstack user create --domain default --password {{ keystone_pass }} cinder 

    - name: cinder role add 
      command: openstack role add --project service --user cinder admin 

    - name: Create the cinder service entity
      command: openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2

    - name: Create the cinder service entity
      command: openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3
