---
  - name:  OpenStack Service_cinder
    hosts: controller01
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    environment:
       OS_PROJECT_DOMAIN_NAME: Default
       OS_USER_DOMAIN_NAME: Default
       OS_PROJECT_NAME: admin
       OS_USERNAME: admin
       OS_PASSWORD: "{{ keystone_pass }}" 
       OS_AUTH_URL: http://{{ bind_ip }}:15000/v3/
       OS_IDENTITY_API_VERSION: 3
       OS_IMAGE_API_VERSION: 2
    tasks:
    - name: Create cinder volumev2 endpoints.
      command: 'openstack endpoint create --region RegionOne volumev2 {{ item.key }} {{ item.value }}' 
      with_dict:
        public: 'http://{{ bind_ip }}:18776/v2/%\(project_id\)s' 
        internal: 'http://{{ bind_ip }}:18776/v2/%\(project_id\)s' 
        admin: 'http://{{ bind_ip }}:18776/v2/%\(project_id\)s'

    - name: Create cinder volumev3 endpoints.
      command: 'openstack endpoint create --region RegionOne volumev3 {{ item.key }} {{ item.value }}'
      with_dict:
        public: 'http://{{ bind_ip }}:18776/v3/%\(project_id\)s'
        internal: 'http://{{ bind_ip }}:18776/v3/%\(project_id\)s'
        admin: 'http://{{ bind_ip }}:18776/v3/%\(project_id\)s'
