---
- name: install python-openstackclient
  hosts: controller
  become: true
  vars_files:
    - /root/okestroiaas/variable/common_vars/main.yml
  tasks:
  - name:
    yum:
      update_cache: yes
      name:
         - python3-openstackclient
      state: present
