---
  - name:  OpenStack Service_Keystone
    hosts: controller
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: ha config file setting
      ini_file:
        dest: /etc/neutron/neutron.conf
        section: DEFAULT 
        option: '{{ item.key }}'
        value: '{{ item.value }}'
      with_dict:
        dhcp_agents_per_network: 3
        max_l3_agents_per_router: 3
