---
  - name:  OpenStack Service neutron-gateway
    hosts: controller
    become: true
    vars_files:
      - /root/okestroiaas/variable/common_vars/main.yml
    tasks:
    - name: Template configuration files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        backup: yes
      with_items:
        - { src: '/root/okestroiaas/template/ml2_conf.ini.j2',dest: '/etc/neutron/plugins/ml2/ml2_conf.ini',owner: 'root',group: 'neutron',mode: '0644'}
        - { src: '/root/okestroiaas/template/openvswitch_agent.ini.j2',dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini',owner: 'root',group: 'neutron',mode: '0644'}
        - { src: '/root/okestroiaas/template/l3_agent.ini.j2',dest: '/etc/neutron/l3_agent.ini',owner: 'root',group: 'neutron',mode: '0644'}
        - { src: '/root/okestroiaas/template/dhcp_agent.ini.j2',dest: '/etc/neutron/dhcp_agent.ini',owner: 'root',group: 'neutron',mode: '0644'}
        - { src: '/root/okestroiaas/template/metadata_agent.ini.j2',dest: '/etc/neutron/metadata_agent.ini',owner: 'root',group: 'neutron',mode: '0644'}
